export const compendiumData = {
  Fashion: {
    Stores: [
      "Thisthingofours",
      "Ln-cc",
      "Arys store",
      "Voostore",
      "Highsnobiety",
      "Lelabostore",
      "Knud Peters",
      "Bstn Store",
      "Centre Commercial",
      "Lagune Cph",
      "Deru",
      "Ka_yo",
      "CareofCarl",
      "Vallgatan12",
    ],
    Brands: [
      "Nanamica",
      "Vinnys loafer",
      "Clints Inc",
      "Kleman",
      "Sebago",
      "Wild bunch",
      "South to west",
      "Maharishi snopants",
      "Merciparis",
      "Packer shoes",
      "Kayo",
      "Thisisneverthat",
      "Cayl",
      "Neithers",
      "Klättermusen",
      "FAT International",
      "8000watt",
      "Solitude",
      "Altra (Norwegisch)",
      "Roa",
      "District Vision",
      "Sacai",
      "Jieda",
      "H beauty and Youth",
      "Rotholz",
      "Jan n June",
      "And wander",
      "Nanga",
      "Gramicci",
      "Danner",
      "TheInternetShop",
      "Merrell",
      "Yayu.world",
      "Tracksuitbae",
      "Huni (mona thomas)",
      "Soulland",
      "Another Aspect",
      "Odlo",
      "Doxa Running",
      "Serena Li",
      "Soeur Paris",
      "Village PM",
      "Attaquer Cycling",
    ],
    Suits: [
      "universal works",
      "NN07",
      "Norse projects",
      "hast paris",
      "Casatlantic",
      "Oliver Spencer",
      "Berner Kühl",
      "Jan Machenhauer",
      "Soshio Tsuki",
      "Marker Ware / Marker",
      "Auralee",
      "Studio Nicholson",
      "Barena Venezia",
      "Mf pen",
      "Lea Boberg",
      "Still by hand",
      "Lemaire",
      "Filippa K",
    ],
  },
  Home: {
    Interior: [
      "Audo",
      "Objekte unserer Tage",
      "Flos",
      "Muuto",
      "DCW Editions Paris",
      "Midgard",
      "Oblist",
      "Tanchen Studio",
      "Grau",
      "Modulor",
      "Standard Products",
      "Gast Studio",
      "Mariotsai",
      "Luce Luce",
      "SGMS Studio",
      "OTKHI Ceramic Factory (Tibilisi)",
    ],
    Kitchen: ["Veark", "Mono", "DUPLEX"],
  },
  Music: {
    "Listening Bars": [
      "Tradr Hifi (HH)",
      "Bambino (PARIS)",
      "Spin (MUC)",
      "Stereophonic (Seoul)",
      "Unkompress (Berlin)",
      "Bar Neiro (Berlin)",
      "Secret Session Thatboii (MUC)",
    ],
    Radios: ["Radio 8000", "NTS", "SCR (Seoul Community Radio)"],
    "Record Shops": ["Otaku Records (HH)"],
    "Nightlife/Clubs": [
      "Blitz MUC",
      "Open Ground Wuppertal",
      "Poing Club Rotterdam",
      "Mia Mao Club Paris",
      "Basement New York",
      "Tokonoma Frankfurt",
      "Blur Brüssel",
      "Sonnenraum Berlin",
      "Porzellanbar Berlin",
      "RSO Berlin",
      "Adrenalin Cologne",
    ],
  },
  Travel: {
    Hotels: ["laspi.life"],
    Guides: ["Trippin Worldwide", "Roadbook.com"],
  },
  Culinary: {
    Bars: ["Chez Jeannette (Paris)"],
    Cafes: ["The basement (HH)", "Kraweel (HH)", "Kante", "Kaffee Stark"],
    Restaurants: ["Maquis (HH)"],
  },
  Jewelry: { Items: ["Elise Estelle", "Simuero", "Migle"] },
  Flowers: { Items: ["other_vase"] },
  "Printed Goods": {
    Magazines: [
      "brandeins",
      "B Magazine",
      "F Magazine",
      "C Magazine",
      "Lürzers Archive",
    ],
    Books: ["Der totale Rausch"],
    Publishers: ["Masala Noir", "ActualSource Books"],
    Posters: [
      "100 beste Plakate",
      "Terracottaprints",
      "Drool Art",
      "Kiblind Atelier",
      "Ines Gradot Studio",
      "Quintal Atelier",
      "Bienvenue Studios",
      "Shrig Shop",
      "Its Nice That",
      "Cancanpress",
    ],
  },
  Mobility: {
    Bikes: ["Assos of Switzerland", "Rondo Bikes", "NS Bikes", "Pinarello"],
  },
  Culture: {
    "Museums & Galerien": [
      "A—Z Berlin",
      "Galerie Oel Früh",
      "Jüdisches Museum Berlin",
    ],
  },
  "Visual Inspiration": {
    Photographers: ["Edward Burnitsky", "Florian Schüppel", "Robbie Lawrence"],
    "Stock Sites": [
      "Death to Stock",
      "Stills.com",
      "Making Pictures",
      "EyeEm",
      "Soot Spiral",
    ],
    Directories: [
      "Connected Archives",
      "Cosmos",
      "Behance",
      "Hydrant directory",
      "research.mouthwash.studio",
    ],
    Artists: [
      "Syd Mead",
      "Seon Gryul",
      "Stephen Smith",
      "Nick Dahlen",
      "Yay Abe",
    ],
  },
  "Creative Tools and Studios": {
    Agencies: [
      "Stockholmdesignlabs.com",
      "Lostproperty.studio",
      "Snask.com",
      "Norgram",
      "Bureau Borsche",
      "Porto Rocha",
      "Ocurens Content",
      "Services Generaux",
    ],
    "Branding & Brand Strategy": [
      "Mark Pollard",
      "operatinglogic.com",
      "deck.gallery",
      "brandingstyleguides.com",
      "Brand.new",
      "The Futur - Chris Do",
    ],
  },
  Impact: {
    NGOs: [
      "HateAid",
      "Correctiv",
      "Laut gegen Nazis e.V.",
      "bcause",
      "Supportyourlocaldealer.org",
      "PRÜF Demos",
    ],
    Banking: ["tomorrow bank"],
  },
};
